### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by oushujun** [yangli557/AnnoSINE#1]
Dear Yang,

Great work! Congratulations!

I am so excited to learn that finally there is a good tool for de novo SINE annotation! Before attempting to try to use it on my side, I notice that the repo does not have a software license. Without a license, it will be difficult to make distributions such as conda. Can you please add one? For open source licensing, usually, people use [MIT](https://opensource.org/licenses/MIT) or the [GNU General Public License](https://www.gnu.org/licenses/gpl-3.0.en.html). Please let me know if you need help.

Best,
Shujun

**Comment by yangli557** [comment]
Dear Prof. Ou,Thanks for your kindly advice and reminder. I will work on the code licence as soon as possible.Best regards,LI Yang---- Replied Message ----FromShujun ***@***.***>Date11/19/2021 10:07 ***@***.***> ***@***.***>Subject[Ext] [yangli557/AnnoSINE] Add license (Issue #1)






This email originated from outside of City University of Hong Kong. Do not respond, click links, or open attachments unless you recognize the sender and know that the content is safe.







Dear Yang,
Great work! Congratulations!
I am so excited to learn that finally there is a good tool for de novo SINE annotation! Before attempting to try to use it on my side, I notice that the repo does not have a software license. Without a license, it will be difficult to make distributions
 such as conda. Can you please add one? For open source licensing, usually, people use
MIT or the 
GNU General Public License. Please let me know if you need help.
Best,
Shujun
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
Triage notifications on the go with GitHub Mobile for 
iOS or 
Android. 
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/yangli557/AnnoSINE/issues/1",
"url": "https://github.com/yangli557/AnnoSINE/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
